version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql

  wp:
    image: wordpress:latest          # pulls the newest WP 6.x + PHP
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      # mount the theme into wp-content (replace “fictioneer” if slug differs)
      - ..:/var/www/html/wp-content/themes/fictioneer
volumes:
  db_data:
